export * from './lib/movie/+state';
export * from './lib/movie/guards/movie.guard';
export * from './lib/movie/movie.module';
export const staticModels = require('./lib/movie/staticModels.json');
export { ViewComponent } from './lib/movie/view/view.component';
export { FormComponent } from './lib/movie/form/form.component';
export { ListComponent } from './lib/movie/list/list.component';
export { HomeComponent } from './lib/movie/home/home.component';
export * from './lib/stakeholder/+state/stakeholder.query';
export * from './lib/stakeholder/+state/stakeholder.store';
export * from './lib/stakeholder/+state/stakeholder.service';
export * from './lib/stakeholder/+state/stakeholder.model';
